spring.application.name=seotool
spring.docker.compose.mode=off

supabase.url=${SUPABASE_URL}
supabase.secret=${SUPABASE_SECRET_KEY}

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

openai.api.key=${OPENAI_API_KEY}
openai.model=${OPENAI_MODEL:gpt-4o-mini}