spring.application.name=seotool
spring.docker.compose.mode=off

supabase.url=${SUPABASE_URL}
supabase.secret=${SUPABASE_SECRET_KEY}

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

gemini.api.key=${GEMINI_API_KEY}
gemini.model=${GEMINI_MODEL:gemini-2.5-flash}

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
